[help]
commands = ['help', 'start']
description = 'Показать это сообщение'

[weather1]
commands = ['w', 'weather', 'погода', 'п']
description = """Получить инфо о погоде
из первого источника.
Если недоступно, проверьте /w2"""

[weather2]
commands = ['w2', 'weather2', 'погода2', 'п2']
description = """Получить инфо о погоде
из второго источника.
Если недоступно, мы в дерьме!"""
